# -*- coding: utf-8 -*-
"""
/***************************************************************************
 population_density_analysis
                                 A QGIS plugin
 automet the calculation process of density population
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-30
        copyright            : (C) 2024 by water
        email                : kaundalyson97@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load population_density_analysis class from file population_density_analysis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .population_density_analysis import population_density_analysis
    return population_density_analysis(iface)
