# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'population_density_analysis_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_population_density_analysisDialogBase(object):
    def setupUi(self, population_density_analysisDialogBase):
        population_density_analysisDialogBase.setObjectName("population_density_analysisDialogBase")
        population_density_analysisDialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(population_density_analysisDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.pushButton = QtWidgets.QPushButton(population_density_analysisDialogBase)
        self.pushButton.setGeometry(QtCore.QRect(80, 60, 171, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(population_density_analysisDialogBase)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 100, 171, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(population_density_analysisDialogBase)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 63, 61, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(population_density_analysisDialogBase)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 100, 61, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(population_density_analysisDialogBase)
        self.pushButton_5.setGeometry(QtCore.QRect(130, 150, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(population_density_analysisDialogBase)
        self.pushButton_6.setGeometry(QtCore.QRect(260, 150, 61, 21))
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(population_density_analysisDialogBase)
        self.button_box.accepted.connect(population_density_analysisDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(population_density_analysisDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(population_density_analysisDialogBase)

    def retranslateUi(self, population_density_analysisDialogBase):
        _translate = QtCore.QCoreApplication.translate
        population_density_analysisDialogBase.setWindowTitle(_translate("population_density_analysisDialogBase", "population_density_analysis"))
        self.pushButton.setText(_translate("population_density_analysisDialogBase", "Select layer"))
        self.pushButton_2.setText(_translate("population_density_analysisDialogBase", "select district"))
        self.pushButton_3.setText(_translate("population_density_analysisDialogBase", "........."))
        self.pushButton_4.setText(_translate("population_density_analysisDialogBase", "........"))
        self.pushButton_5.setText(_translate("population_density_analysisDialogBase", "output"))
        self.pushButton_6.setText(_translate("population_density_analysisDialogBase", "........"))
