# # -*- coding: utf-8 -*-
# """
# /***************************************************************************
#  population_density_analysisDialog
#                                  A QGIS plugin
#  automet the calculation process of density population
#  Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
#                              -------------------
#         begin                : 2024-11-30
#         git sha              : $Format:%H$
#         copyright            : (C) 2024 by water
#         email                : kaundalyson97@gmail.com
#  ***************************************************************************/

# /***************************************************************************
#  *                                                                         *
#  *   This program is free software; you can redistribute it and/or modify  *
#  *   it under the terms of the GNU General Public License as published by  *
#  *   the Free Software Foundation; either version 2 of the License, or     *
#  *   (at your option) any later version.                                   *
#  *                                                                         *
#  ***************************************************************************/
# """

# import os

# from qgis.PyQt import uic
# from qgis.PyQt import QtWidgets

# # This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
# FORM_CLASS, _ = uic.loadUiType(os.path.join(
#     os.path.dirname(__file__), 'population_density_analysis_dialog_base.ui'))


# class population_density_analysisDialog(QtWidgets.QDialog, FORM_CLASS):
#     def __init__(self, parent=None):
#         """Constructor."""
#         super(population_density_analysisDialog, self).__init__(parent)
#         # Set up the user interface from Designer through FORM_CLASS.
#         # After self.setupUi() you can access any designer object by doing
#         # self.<objectname>, and you can use autoconnect slots - see
#         # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
#         # #widgets-and-dialogs-with-auto-connect
#         self.setupUi(self)



# # # -*- coding: utf-8 -*-



import os
from qgis.PyQt import uic, QtWidgets
from qgis.core import QgsDataSourceUri, QgsVectorLayer
from qgis.PyQt.QtWidgets import QMessageBox

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "population_density_analysis_dialog_base.ui")
)

class population_density_analysisDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(population_density_analysisDialog, self).__init__(parent)
        self.setupUi(self)
        self.pushButton.clicked.connect(self.select_district)

    def select_district(self):
        """Fetch and display districts from PostgreSQL."""
        try:
            connection_uri = QgsDataSourceUri()
            connection_uri.setConnection(
                "localhost", "5432", "population_density_calculator", "postgres", "1234"
            )
            connection_uri.setDataSource("public", "city_popn_EAS-2018-3", "geom")
            layer = QgsVectorLayer(connection_uri.uri(), "Districts Layer", "postgres")

            if not layer.isValid():
                raise Exception("Failed to load layer. Check your database connection.")

            districts = {feature["DIST_NAME"] for feature in layer.getFeatures() if feature["DIST_NAME"]}
            if districts:
                QMessageBox.information(self, "Districts", "\n".join(sorted(districts)))
            else:
                QMessageBox.warning(self, "No Districts", "No districts found in the data.")

        except Exception as e:
            QMessageBox.critical(self, "Error", f"An error occurred: {str(e)}")
